# Generated by Django 6.0.1 on 2026-01-15 15:10

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('res_name', models.CharField(max_length=100)),
                ('res_address', models.TextField()),
                ('res_contact_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$')])),
                ('google_location_url', models.URLField(blank=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(default=datetime.time(10, 0))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('restaurant_image', models.ImageField(blank=True, upload_to='restaurants/')),
                ('fssai_license_no', models.CharField(max_length=30, unique=True)),
                ('fssai_license_url', models.FileField(upload_to='fssai/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('gst_registration_no', models.CharField(max_length=30, unique=True)),
                ('gst_registration_url', models.FileField(upload_to='gst/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('verification_status', models.CharField(choices=[('not_verified', 'Not Verified'), ('verified', 'Verified')], default='not_verified', max_length=12)),
                ('annual_fee_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('fee_due_date', models.DateField(blank=True, null=True)),
                ('is_visible_to_users', models.BooleanField(default=True, help_text='Show in user feed')),
                ('current_checkedin_guests', models.PositiveIntegerField(default=0)),
                ('total_tables', models.PositiveIntegerField(default=0)),
                ('crowd_status', models.CharField(choices=[('empty', 'Empty'), ('low', 'Low'), ('busy', 'Busy'), ('full', 'Full')], default='empty', max_length=10)),
                ('last_crowd_update', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.city')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_owned', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.state')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_diners', models.FloatField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100, unique=True)),
                ('upi_registered_name', models.CharField(max_length=100)),
                ('pan_no', models.CharField(max_length=10)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
