# Generated by Django 6.0.1 on 2026-01-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantanalytics',
            unique_together={('restaurant', 'date')},
        ),
    ]
