# Generated by Django 6.0.1 on 2026-01-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('restaurant', '0002_alter_restaurant_is_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockpayment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='mockpayment',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=50),
        ),
        migrations.AddField(
            model_name='mockpayment',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurant.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockpayment',
            name='transaction_id',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mockpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mockpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
