# Generated by Django 6.0.1 on 2026-01-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_mockpayment_order_id_and_more'),
        ('restaurant', '0002_alter_restaurant_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockpayment',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurant.restaurant'),
        ),
    ]
