# Generated by Django 6.0.1 on 2026-01-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('image_url', models.ImageField(blank=True, upload_to='team_members/')),
                ('linkedin', models.URLField(blank=True, max_length=300)),
                ('github', models.URLField(blank=True, max_length=300)),
                ('is_leader', models.BooleanField(default=False)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
